### ISSUE TITLE
[Bug] failed to compile `NtHiM v0.1.3`

### ISSUE THREAD

**Issue by remonsec** [TheBinitGhimire/NtHiM#19]
Hello
I am facing this error. used this command `cargo install NtHiM`

![error](https://user-images.githubusercontent.com/54717234/150397336-80d72c6e-0d25-4eda-a9db-70b2ebe96766.png)

**Comment by TheBinitGhimire** [comment]
Hello @remonsec,

This issue occurs, because **`cargo install NtHiM`** ignores the **Cargo.lock** file in **NtHiM**, and tries to figure out and use newer version of the dependencies defined in the **Cargo.toml** file.

In this case, [**Cargo.toml**](https://github.com/TheBinitGhimire/NtHiM/blob/0.1.3/Cargo.toml#L21) and [**Cargo.lock**](https://github.com/TheBinitGhimire/NtHiM/blob/0.1.3/Cargo.lock#L94-L124) files have defined the version **`v3.0.0-beta.2`** for **clap**, however **cargo** tries to make use of **clap `v3.0.10`**, and this newer version appears to be using the **`help`** method instead of the **`about`** method, that leads to the issue.

You can fix this issue by using the **`--locked`** flag during installation, i.e. **`cargo install --locked NtHiM`**, which will force **cargo** to use the version defined in [**Cargo.toml**](https://github.com/TheBinitGhimire/NtHiM/blob/0.1.3/Cargo.toml#L21) and [**Cargo.lock**](https://github.com/TheBinitGhimire/NtHiM/blob/0.1.3/Cargo.lock#L94-L124) files.

I will start implementing the **help** method from the upcoming release of **NtHiM**, as required by the newer releases of **clap**.

## Failure during Installation (`cargo install NtHiM`)
### clap `v3.0.10` being used!
![clap `v3.0.10` being used!](https://user-images.githubusercontent.com/20013689/150407210-f7bc5821-c0f1-4a44-a88b-57f98b77d343.png)

### Failure Message!
![Failure Message!](https://user-images.githubusercontent.com/20013689/150407374-1169f91c-cf0e-483e-99a9-e2daeeadb4d8.png)

## Successful Installation (`cargo install --locked NtHiM`)
### clap `v3.0.0-beta.2` being used!
![clap `3.0.0-beta.2` being used!](https://user-images.githubusercontent.com/20013689/150408258-2114766d-4f96-4f4a-adc6-8304163a296e.png)

### Successfully Installed!
![Successfully Installed!](https://user-images.githubusercontent.com/20013689/150408825-8ddde1c3-2915-4384-8f0f-583bf1797498.png)

Thank you for opening up this issue!

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello @remonsec,

The new release of **NtHiM**, i.e. [**v0.1.4**](https://github.com/TheBinitGhimire/NtHiM/releases/tag/0.1.4), is published now, which includes the support for the methods available in the latest version of **clap**, i.e. **`clap v3.0.10`**.

The guidelines I provided earlier would help you in successfully installing **NtHiM v0.1.3**. With this new release, the default command would work fine as well as you did. So, if you are willing to try out this new release, you shall skip the guidelines.

I hope you would try installing **NtHiM v0.1.4** using the same command that you used earlier, and let me know if you are still facing any issues during the installation.

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello @remonsec,

The new release of **NtHiM**, i.e. [**v0.1.4**](https://github.com/TheBinitGhimire/NtHiM/releases/tag/0.1.4), is published now, which includes the support for the methods available in the latest version of **clap**, i.e. **`clap v3.0.10`**.

The guidelines I provided earlier would help you in successfully installing **NtHiM v0.1.3**. With this new release, the default command would work fine as well as you did. So, if you are willing to try out this new release, you shall skip the guidelines.

I hope you would try installing the latest version of **NtHiM**, i.e. **`NtHiM v0.1.4`**, using the same command that you used earlier, and let me know if you are still facing any issues during the installation.

Thanks,
@TheBinitGhimire

**Comment by gprime31** [comment]
I had same problem
update rust to fix
![2022-01-21_08-27](https://user-images.githubusercontent.com/44535257/150534893-654f7d26-4d08-4a82-93ab-959599ae8de5.png)

**Comment by TheBinitGhimire** [comment]
Hello @gprime31,

Thank you for providing the information that Rust/Cargo would have helped in fixing this problem too! I will mention this issue ID as well in the commit message along with #12 and #21 for the documentation update.

Thanks,
@TheBinitGhimire
