### ISSUE TITLE
Increase platform detection

### ISSUE THREAD

**Issue by mzfr** [TheBinitGhimire/NtHiM#2]
Hey,

I am not good with rust but I noticed that you had the platform detection JSON hardcoded in [platform.rs](https://github.com/TheBinitGhimire/NtHiM/blob/main/src/platforms.rs#L15).

It would be nice to provide a separate JSON file that will contain all the information. This way people can also use their custom list.

If you want you can take a look at one of my tools i.e [takeover](https://github.com/mzfr/takeover) in that I have a file named `providers.json` which was made by scraping the can-i-take-over-xyz repository's readme combining it with subjack's [fingerprint.json](https://github.com/haccer/subjack/blob/master/fingerprints.json) and subOver's [provider.json](https://github.com/Ice3man543/SubOver/blob/master/providers.json)

**Comment by naryal2580** [comment]
@mzfr Thanks a lot for sharing it here, I am going through all the URLs that you've provided and will update the remote repository (https://github.com/Pentester-Nepal/Subdomain-Takeover-Signatures/)

AND since, I'd simply copy pasted the JSON content within `platform.rs` and according to @TheBinitGhimire's `README.md` it was taken from (https://github.com/EdOverflow/can-i-take-over-xyz) that's why, I've just credited a single source. As soon as I include it from all of the destinations you've provided. I'll credit them too (including your repo. ngl, loved it!) 😃

**Comment by TheBinitGhimire** [comment]
Hello @mzfr,

As @naryal2580 mentioned earlier, the issue you have opened appears to be resolved now, since users can now remotely fetch the latest signatures from the remote repository, and also add their own custom signatures in the **`signatures.json`** file to use with **NtHiM**.

If you are wondering where you can find the **`signatures.json`** file for **NtHiM**, then the following information shall be helpful for you:
* Microsoft Windows: **`%LOCALAPPDATA%\NtHiM\signatures.json`**
* Linux/*BSD: **`~/.cache/NtHiM/signatures.json`** 
* macOS: **`~/Library/Caches/signatures.json`**

With these information, I believe your issue has been resolved now, and I will be closing it for now.

Thank You opening up this issue, and providing an opportunity to include useful functionalities within **NtHiM**!

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello @mzfr,

As @naryal2580 mentioned earlier, the issue you have opened appears to be resolved now, since users can now remotely fetch the latest signatures from the remote repository, and also add their own custom signatures in the **`signatures.json`** file to use with **NtHiM**.

If you are wondering where you can find the **`signatures.json`** file for **NtHiM**, then the following information shall be helpful for you:
* Microsoft Windows: **`%LOCALAPPDATA%\NtHiM\signatures.json`**
* Linux/*BSD: **`~/.cache/NtHiM/signatures.json`** 
* macOS: **`~/Library/Caches/signatures.json`**

With these information, I believe your issue has been resolved now, and I will be closing it for now.

Thank You for opening up this issue, and providing an opportunity to include useful functionalities within **NtHiM**!

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello @mzfr,

As @naryal2580 mentioned earlier, the issue you have opened appears to be resolved now, since users can now remotely fetch the latest signatures from the remote repository, and also add their own custom signatures in the **`signatures.json`** file to use with **NtHiM**.

If you are wondering where you can find the **`signatures.json`** file for **NtHiM**, then the following information shall be helpful for you:
* Microsoft Windows: **`%LOCALAPPDATA%\NtHiM\signatures.json`**
* Linux/*BSD: **`~/.cache/NtHiM/signatures.json`** 
* macOS: **`~/Library/Caches/signatures.json`**

With these information, I believe your issue has been resolved now, and I have closed it for now.

Thank You opening up this issue, and providing an opportunity to include useful functionalities within **NtHiM**!

Thanks,
@TheBinitGhimire
